[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_bounty_board = "8wEnvDw8rQoWQXsCvE3ALt5bEuB8FeA8A52N5Uacjayh"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id_2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
