[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_bounty_board = "H72kd3NLBGpsc1DcPk5bnjJtu7BXzwNSDFa2BeVQaTEL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/home/qiao-wen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
